import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {QueryClient, QueryClientProvider} from "@tanstack/react-query";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

const inter = Inter({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className + ' bg-gray-900 text-gray-200 antialiased min-h-screen flex flex-col'}>
                <ReactQueryProvider>
                    <Header />
                    <main className="flex-1">
                        {children}
                    </main>
                    <Footer />
                </ReactQueryProvider>
            </body>
        </html>
    )
}
